"""add_wards_beds_admissions

Revision ID: 161d4b23d204
Revises: bc5eaf1bf983
Create Date: 2026-08-19 08:49:24.304433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161d4b23d204'
down_revision = 'bc5eaf1bf983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ward_type', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('beds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('bed_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ward_id', 'bed_number', name='uq_beds_ward_number')
    )
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beds_ward_id'), ['ward_id'], unique=False)

    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('admitting_doctor_id', sa.Integer(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(), nullable=False),
    sa.Column('discharged_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admitting_doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admissions_bed_id'), ['bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('uq_admissions_bed_active', ['bed_id'], unique=True, sqlite_where=sa.text('discharged_at IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index('uq_admissions_bed_active', sqlite_where=sa.text('discharged_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_bed_id'))

    op.drop_table('admissions')
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beds_ward_id'))

    op.drop_table('beds')
    op.drop_table('wards')
    # ### end Alembic commands ###
