"""add email OTP 2FA field

Revision ID: 193c531a7adb
Revises: 41cf7bf49b88
Create Date: 2026-08-28 17:25:55.778791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193c531a7adb'
down_revision = '41cf7bf49b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_otp_enabled', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_otp_enabled')

    # ### end Alembic commands ###
