"""add reminder_sent_at to appointments

Revision ID: 41cf7bf49b88
Revises: 490634984c72
Create Date: 2026-08-26 00:34:46.347871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cf7bf49b88'
down_revision = '490634984c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent_at')

    # ### end Alembic commands ###
