"""add_patient_profile

Revision ID: 841cda86b399
Revises: bff8b8ad2875
Create Date: 2026-08-19 08:25:30.489630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841cda86b399'
down_revision = 'bff8b8ad2875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###

    # Backfill: any pre-existing user with role='patient' (i.e. everyone
    # registered before this migration, since 'patient' was already the
    # default) needs a profile row too, or app/patients/routes.py's
    # `filter_by(user_id=...).first()` lookups will 404 for them. Raw SQL,
    # not the ORM model, since migrations must stay decoupled from
    # app/models.py as it changes over time.
    op.execute(
        """
        INSERT INTO patient_profiles (user_id, created_at)
        SELECT id, CURRENT_TIMESTAMP FROM users WHERE role = 'patient'
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_profiles_user_id'))

    op.drop_table('patient_profiles')
    # ### end Alembic commands ###
