"""add_appointments

Revision ID: bc5eaf1bf983
Revises: 5497a14e548a
Create Date: 2026-08-19 08:41:52.723742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5eaf1bf983'
down_revision = '5497a14e548a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index('ix_appointments_doctor_window', ['doctor_id', 'scheduled_start', 'scheduled_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index('ix_appointments_patient_window', ['patient_id', 'scheduled_start'], unique=False)
        batch_op.create_index('uq_appointments_doctor_start_active', ['doctor_id', 'scheduled_start'], unique=True, sqlite_where=sa.text("status != 'cancelled'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('uq_appointments_doctor_start_active', sqlite_where=sa.text("status != 'cancelled'"))
        batch_op.drop_index('ix_appointments_patient_window')
        batch_op.drop_index(batch_op.f('ix_appointments_patient_id'))
        batch_op.drop_index('ix_appointments_doctor_window')
        batch_op.drop_index(batch_op.f('ix_appointments_doctor_id'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
